### ISSUE TITLE
Level Extender spams informational messages to SMAPI console

### ISSUE THREAD

**Issue by rmenessec** [unidarkshin/Stardew-Mods#13]
Please disable, or add support for a user-editable config.json to disable this and other debug output. Thanks!

**Comment by unidarkshin** [comment]
I purposely left this in so that people could receive updates on gaining xp. The smapi log is not really supposed to be monitored but I suppose I could add that functionality.

**Comment by rmenessec** [comment]
I'd appreciate a disabled-by-default toggle. I'm in the process of reporting a huge whack of errors in other mods, and Level Extender's both cluttering up the display as I'm looking for real errors and increasing the size of the logs I'm uploading to https://log.smapi.io/
